version: '3.9'

services:
  backend:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./data:/app/data
    depends_on:
      - db

  frontend-html:
    build:
      context: ./public/html
      dockerfile: ./Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - backend

  frontend-css:
    build:
      context: ./public/css
      dockerfile: ./Dockerfile
    ports:
      - "8081:80"
    depends_on:
      - backend

  frontend-js:
    build:
      context: ./public/js
      dockerfile: ./Dockerfile
    ports:
      - "8082:80"
    depends_on:
      - backend

  db:
    image: nouchka/sqlite3
    volumes:
      - db_data:/data
    command: ["sleep", "infinity"]

volumes:
  db_data:
